[package]
name = "rait-updown"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rtnetlink = "0.12.0"
netlink-packet-route = "0.15.0"
futures = "0.3.11"
tokio = { version = "1.9.0", features = ["sync", "rt-multi-thread", "macros"] }
nix ="*"